name: API Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Newman + Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Download Postman Collection
        run: |
          curl --location \
          --header "X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}" \
          "https://api.getpostman.com/collections/${{ secrets.POSTMAN_COLLECTION_UID }}" \
          --output collection.json

      - name: Run API Tests
        run: |
          newman run collection.json -e environment.json -r cli,html \
            --env-var "API_KEY=${{ secrets.OPENWEATHER_API_KEY }}" \
            --env-var "BASE_URL=${{ secrets.OPENWEATHER_BASE_URL }}"

      - name: Upload Newman Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.html
